server:
  port: 10010 # 服务端口
spring:
  application:
    name: leyou-gateway # 指定微服务应用名称，会在Eureka中显示
eureka:
  client:
    registry-fetch-interval-seconds: 5  # 获取服务列表的周期：5s
    service-url:  # EurekaServer的地址，服务端的端口为10086
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api    # 添加路由路径前缀
  routes:   #路由
    item-service: /item/**    # 商品微服务的映射路径