server:
  port: 8081 #商品服务端口
spring:
  application:
    name: item-service  #商品微服务名称
  datasource:   #数据源
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&characterEncoding=UTF-8 #数据库地址
    username: root  #数据库用户名
    password: 123456  #密码
eureka:
  client:
    service-url: # EurekaServer的地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  # 心跳时间：5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 15  # 过期时间：10秒不发送就过期
mybatis:
  type-aliases-package: com.leyou.item.pojo   # mybatis别名扫描,将com.leyou.item.pojo建在item-interface接口下，因为item-service依赖了item-interface，能够扫描的到。